spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-location: "classpath:/config"
          #search-location: "file:G:/Java 2024/Learning microservices/Configuration management/advnace springboot configuration by spring cloud/configuration"
        git:
          uri: "https://github.com/salmansiddiqui75/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
server:
  port: 8071